import { atom } from "recoil";

type Diameter = 225 | 250 | 280 | 315 | 355 | 400 | 500;
type Sdr = 11 | 13.6 | 17;

export interface Bushing {
  id: number;
  name: string;
  type: "cast short" | "cast elongated" | "welded elongated";
  elongated: boolean;
  d: Diameter;
  sdr: Sdr;
  price: number;
  amountInStock: number;
}

export const productListState = atom<Bushing[]>({
  key: "productList",
  default: [
    {
      id: 0,
      name: "Втулка литая удлиненная под фланец (Бурт)",
      type: "cast elongated",
      elongated: true,
      d: 225,
      price: 1256,
      sdr: 11,
      amountInStock: 10,
    },
    {
      id: 1,
      name: "Втулка литая удлиненная под фланец (Бурт)",
      type: "cast elongated",
      elongated: true,
      d: 225,
      price: 1100,
      sdr: 13.6,
      amountInStock: 10,
    },
    {
      id: 2,
      name: "Втулка литая удлиненная под фланец (Бурт)",
      type: "cast elongated",
      elongated: true,
      d: 225,
      price: 900,
      sdr: 17,
      amountInStock: 10,
    },
    {
      id: 3,
      name: "Втулка литая удлиненная под фланец (Бурт)",
      type: "cast elongated",
      elongated: true,
      d: 250,
      price: 1850,
      sdr: 11,
      amountInStock: 10,
    },
    {
      id: 4,
      name: "Втулка литая удлиненная под фланец (Бурт)",
      type: "cast elongated",
      elongated: true,
      d: 250,
      price: 1750,
      sdr: 13.6,
      amountInStock: 10,
    },
    {
      id: 5,
      name: "Втулка литая удлиненная под фланец (Бурт)",
      type: "cast elongated",
      elongated: true,
      d: 250,
      price: 1200,
      sdr: 17,
      amountInStock: 10,
    },
    {
      id: 6,
      name: "Втулка литая удлиненная под фланец (Бурт)",
      type: "cast elongated",
      elongated: true,
      d: 280,
      price: 2200,
      sdr: 11,
      amountInStock: 10,
    },
    {
      id: 7,
      name: "Втулка литая удлиненная под фланец (Бурт)",
      type: "cast elongated",
      elongated: true,
      d: 280,
      price: 2100,
      sdr: 13.6,
      amountInStock: 10,
    },
    {
      id: 8,
      name: "Втулка литая удлиненная под фланец (Бурт)",
      type: "cast elongated",
      elongated: true,
      d: 280,
      price: 2000,
      sdr: 17,
      amountInStock: 10,
    },

    {
      id: 9,
      name: "Втулка литая удлиненная под фланец (Бурт)",
      type: "cast elongated",
      elongated: true,
      d: 315,
      price: 2700,
      sdr: 11,
      amountInStock: 10,
    },
    {
      id: 10,
      name: "Втулка литая удлиненная под фланец (Бурт)",
      type: "cast elongated",
      elongated: true,
      d: 315,
      price: 2500,
      sdr: 13.6,
      amountInStock: 10,
    },
    {
      id: 11,
      name: "Втулка литая удлиненная под фланец (Бурт)",
      type: "cast elongated",
      elongated: true,
      d: 315,
      price: 2300,
      sdr: 17,
      amountInStock: 10,
    },
    {
      id: 12,
      name: "Втулка литая удлиненная под фланец (Бурт)",
      type: "cast elongated",
      elongated: true,
      d: 355,
      price: 5200,
      sdr: 11,
      amountInStock: 10,
    },
    {
      id: 13,
      name: "Втулка литая удлиненная под фланец (Бурт)",
      type: "cast elongated",
      elongated: true,
      d: 355,
      price: 4900,
      sdr: 13.6,
      amountInStock: 10,
    },
    {
      id: 14,
      name: "Втулка литая удлиненная под фланец (Бурт)",
      type: "cast elongated",
      elongated: true,
      d: 355,
      price: 3950,
      sdr: 17,
      amountInStock: 10,
    },
    {
      id: 15,
      name: "Втулка литая удлиненная под фланец (Бурт)",
      type: "cast elongated",
      elongated: true,
      d: 400,
      price: 6100,
      sdr: 11,
      amountInStock: 10,
    },
    {
      id: 16,
      name: "Втулка литая удлиненная под фланец (Бурт)",
      type: "cast elongated",
      elongated: true,
      d: 400,
      price: 5500,
      sdr: 13.6,
      amountInStock: 10,
    },
    {
      id: 17,
      name: "Втулка литая удлиненная под фланец (Бурт)",
      type: "cast elongated",
      elongated: true,
      d: 400,
      price: 4500,
      sdr: 17,
      amountInStock: 10,
    },
    {
      id: 18,
      name: "Втулка литая удлиненная под фланец (Бурт)",
      type: "cast elongated",
      elongated: true,
      d: 500,
      price: 13000,
      sdr: 11,
      amountInStock: 10,
    },
    {
      id: 19,
      name: "Втулка литая удлиненная под фланец (Бурт)",
      type: "cast elongated",
      elongated: true,
      d: 500,
      price: 12200,
      sdr: 13.6,
      amountInStock: 10,
    },
    {
      id: 20,
      name: "Втулка литая удлиненная под фланец (Бурт)",
      type: "cast elongated",
      elongated: true,
      d: 500,
      price: 11200,
      sdr: 17,
      amountInStock: 10,
    },
  ],
});
